# Generated by Django 3.2.13 on 2022-06-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corr', models.PositiveIntegerField()),
                ('mark', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=20)),
                ('needs', models.CharField(max_length=20)),
                ('civil_works_need', models.BooleanField(default=False)),
                ('add_info', models.TextField(max_length=110)),
            ],
        ),
    ]
