# Generated by Django 3.2.13 on 2022-06-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junction',
            name='corr',
            field=models.CharField(max_length=2),
        ),
    ]
