# Generated by Django 3.2.13 on 2022-06-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0002_alter_junction_corr'),
    ]

    operations = [
        migrations.AddField(
            model_name='junction',
            name='cables_cut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='junction',
            name='corr',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='junction',
            name='mark',
            field=models.CharField(max_length=6),
        ),
    ]
