# Generated by Django 3.2.13 on 2022-06-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0003_auto_20220605_2042'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='junction',
            table='Junction',
        ),
    ]
