# Generated by Django 3.2.13 on 2022-06-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0004_alter_junction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junction',
            name='add_info',
            field=models.TextField(default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='junction',
            name='needs',
            field=models.CharField(default='', max_length=20),
        ),
    ]
