# Generated by Django 3.2.13 on 2022-06-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0007_auto_20220607_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junction',
            name='status',
        ),
        migrations.AddField(
            model_name='junction',
            name='status',
            field=models.ManyToManyField(to='junc.Status'),
        ),
    ]
