# Generated by Django 3.2.13 on 2022-06-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0008_auto_20220607_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junction',
            name='status',
        ),
        migrations.AddField(
            model_name='junction',
            name='status',
            field=models.CharField(choices=[('PR', 'Pun Rezim'), ('PT', 'Part Time')], default='PR', max_length=2),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
