# Generated by Django 3.2.13 on 2022-06-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0009_auto_20220607_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junction',
            name='status',
            field=models.CharField(choices=[('Pun Rezim', 'Pun Rezim'), ('Part Time', 'Part Time')], default='Pun Rezim', max_length=20),
        ),
    ]
