# Generated by Django 3.2.13 on 2022-06-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0010_alter_junction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junction',
            name='status',
            field=models.CharField(choices=[('Pun Rezim', 'Pun Rezim'), ('Part Time', 'Part Time'), ('Nema Struje', 'Nema Struje'), ('Ugasena', 'Ugasena')], default='Pun Rezim', max_length=20),
        ),
    ]
