# Generated by Django 3.2.13 on 2022-06-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0011_alter_junction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='junction',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='junction',
            name='name_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='junction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
