# Generated by Django 3.2.13 on 2022-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0012_auto_20220608_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
