# Generated by Django 3.2.13 on 2022-06-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0013_alter_junction_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Supadmin'), (2, 'Tech'), (3, 'Guest')], null=True)),
            ],
        ),
    ]
