# Generated by Django 3.2.13 on 2022-06-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junc', '0014_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
