# Generated by Django 3.2.13 on 2022-06-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedal_name', models.CharField(max_length=22)),
                ('pedal_cat', models.CharField(max_length=15)),
                ('pedal_year', models.PositiveIntegerField(blank=True, default='')),
            ],
        ),
    ]
