# Generated by Django 3.2.13 on 2022-06-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stomps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedal',
            table='Pedal',
        ),
    ]
